language: csharp
solution: MassSpectrometry.sln
install:
  - nuget restore MassSpectrometry.sln
  - nuget install NUnit.Console -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=NoMassSpecFiles MassSpectrometry.sln 
  - mono ./testrunner/NUnit.ConsoleRunner.*/tools/nunit3-console.exe ./Test/bin/Debug/Test.dll
